### PR TITLE
Allow customisation of worker name in environment

### PR DESCRIPTION
**Pull request by jacobtomlinson**
This PR allows you to customise the worker name template with the environment variable `DASKERNETES_WORKER_NAME_TEMPLATE`. If not specified it falls back to `dask-{user}-{uuid}`.

The template is then formatted with `user` and `uuid` as before but also it unpacks `os.environ` to allow the use of environment variables in the template.

For example in my use case I'm keen to configure the template to `dask-{JUPYTERHUB_USER}-{uuid}` as the `user` is always `jovyan`.

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks good to me.  I recommend a small test similar to this one:

```python
def test_diagnostics_link_env_variable(pod_spec, loop, ns):
    pytest.importorskip('bokeh')
    config['diagnostics-link'] = 'foo-{USER}-{port}'
    try:
        with KubeCluster(pod_spec, loop=loop, namespace=ns) as cluster:
            port = cluster.scheduler.services['bokeh'].port
            cluster._ipython_display_()
            box = cluster._cached_widget

            link = box.children[0]
            assert 'foo-' + getpass.getuser() + '-' + str(port) in link.value
            assert 'href' in link.value
    finally:
        del config['diagnostics-link']
```

If we start doing this with many config variables then we might consider adopting the single-line:

    worker_name_template = config.get('worker-name-template', 'dask-{user}-{uuid}')

Additionally we should keep a list of these options somewhere.  Currently that list is maintained here: http://daskernetes.readthedocs.io/en/latest/#configuration

**Comment by jacobtomlinson** [comment]
Thanks for the quick review. 

Yeah I read the code back after submitting and thought "why didn't I just use `.get()`?.

I'll get the test added and update the docs.

**Comment by mrocklin** [comment]
This looks good to me.  Final question: do we want to use `DASKERNETES_WORKER_NAME` instead of `DASKERNETES_WORKER_NAME_TEMPLATE`?  I believe that the use of template in `DASKERNETES_WORKER_TEMPLATE` before referred to the kubernetes specification.  If it's safe to shorten the name here that might be nice.  I don't have strong feelings here though.

**Comment by mrocklin** [comment]
I'm looking into the test failures.  They seem to be unrelated.

**Comment by jacobtomlinson** [comment]
Happy to shorten! 

I was being explicit that it is a template and therefore you can use the `{variable}` notation. However I see `DASKERNETES_DIAGNOSTICS_LINK` is the same and doesn't feel the need to say it is a template. I'll drop the suffix and push again.

Yeah didn't think it was me, looked to be timeouts on the main tests.

**Comment by jacobtomlinson** [comment]
@mrocklin do you need me to do any more to this? Not sure if there's anything I can do to get the tests passing.

**Comment by mrocklin** [comment]
Nope, you're good.  I'm working on tests now.  I'll merge this after that goes in.  I'll explicitly ping you if anything else needs to happen.  Thanks for working on this.

**Comment by jacobtomlinson** [comment]
Thanks! No probs!

**Comment by mrocklin** [comment]
Merging.  Thanks @jacobtomlinson !

**Comment by jacobtomlinson** [comment]
🎉

Thanks for removing the extra space 😂.

**Pull request merged**
